-- Control Plane schema.
--
-- Three tables per the multi-tenant migration Phase 2 plan.
-- This file is applied by Migrate() on boot when schema_migrations
-- is empty. Post-Phase-3 additions land as numbered follow-ups in
-- migrate.go the same way the Data Plane's migrations do.

-- Bootstrap version tracking. Same convention as the Data Plane.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version    INTEGER PRIMARY KEY,
    name       TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── platform_users ───────────────────────────────────────────────
--
-- Superadmin accounts for the Control Plane. Deliberately NOT the
-- same table as any Data Plane's users — a compromise on a single
-- Data Plane must not grant Control Plane access. Roles are limited
-- to superadmin variants; per-client reviewers live in each Data
-- Plane's users table (until Phase 3 moves reviewers here too).
CREATE TABLE IF NOT EXISTS platform_users (
    id                       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username                 TEXT NOT NULL UNIQUE,
    password_hash            TEXT NOT NULL,
    role                     TEXT NOT NULL CHECK (role IN ('superadmin')),
    display_name             TEXT NOT NULL,
    email                    TEXT,
    disabled_at              TIMESTAMPTZ,
    password_change_required SMALLINT NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_platform_users_email_ci
    ON platform_users(lower(email))
    WHERE email IS NOT NULL AND email <> '';

-- ─── clients_registry ─────────────────────────────────────────────
--
-- The list of every Data Plane the Control Plane knows about. One
-- row per client (NTA, SSC, etc.). api_url + api_key are the
-- connection info the federated proxy uses to reach that Data
-- Plane's /internal/* surface.
--
-- kyc_review_mode is duplicated here from what the Data Plane will
-- eventually hold on its own clients table — the Control Plane needs
-- to know it to route KYC decisions (Phase 3) without a round-trip.
--
-- status governs whether the federated dashboard queries this Data
-- Plane. 'active' = include. 'suspended' = skip in metrics fan-out
-- but keep the row for reactivation. 'deleted' = soft-delete for
-- audit trail preservation.
CREATE TABLE IF NOT EXISTS clients_registry (
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL UNIQUE,
    kyc_review_mode   TEXT NOT NULL DEFAULT 'admin'
                      CHECK (kyc_review_mode IN ('admin','client','both')),
    status            TEXT NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active','suspended','deleted')),
    -- Data Plane's public API URL. Trailing slash stripped by the
    -- CRUD handler so federated calls can concatenate paths safely.
    api_url           TEXT NOT NULL,
    -- Shared secret this Control Plane presents in the
    -- X-Internal-API-Key header when calling the Data Plane's
    -- /internal/* surface. Generated by the Control Plane at client
    -- creation time; the same value must be set as INTERNAL_API_KEY
    -- on the Data Plane's env file. Rotation is a two-sided update.
    api_key           TEXT NOT NULL,
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clients_registry_status
    ON clients_registry(status)
    WHERE status <> 'deleted';

-- ─── institution_applications ─────────────────────────────────────
--
-- The CENTRAL KYC queue. When an institute registers via
-- apply.trustview.in (Phase 3), the row lands here — not on the
-- Data Plane. It stays here until the KYC decision fully lands, at
-- which point the Control Plane fires /internal/orgs/create on the
-- target Data Plane and the actual org+admin rows land there.
--
-- Structure mirrors the Data Plane's institution_applications table
-- so the migration in Phase 3 is a straight column-for-column copy.
-- Any schema drift between the two would be a migration hazard —
-- keep in lockstep.
--
-- target_client_id is the routing lever: when set, the application
-- was addressed at a specific board (deep-linked registration or
-- auto-attach with a single visible client). When NULL, the
-- superadmin still needs to route.
CREATE TABLE IF NOT EXISTS institution_applications (
    id                       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status                   TEXT NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('draft','pending','approved','rejected')),
    -- Which Data Plane this KYC will provision into on approval.
    target_client_id         BIGINT REFERENCES clients_registry(id),
    -- Institution basics
    institution_name         TEXT NOT NULL,
    institution_type         TEXT NOT NULL,
    aishe_code               TEXT,
    pan                      TEXT,
    year_established         INTEGER,
    affiliation_body         TEXT,
    approx_student_count     INTEGER,
    -- Address
    address_line1            TEXT NOT NULL,
    address_line2            TEXT,
    city                     TEXT NOT NULL,
    district                 TEXT,
    state                    TEXT NOT NULL,
    pin_code                 TEXT NOT NULL,
    -- Head of institution
    head_name                TEXT NOT NULL,
    head_designation         TEXT NOT NULL,
    head_email               TEXT NOT NULL,
    head_mobile              TEXT NOT NULL,
    -- Review trail
    reviewed_by_user_id      BIGINT REFERENCES platform_users(id),
    reviewed_at              TIMESTAMPTZ,
    review_note              TEXT,
    submitter_ip             TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique-per-identity for active rows so a rejected applicant can't
-- register again with the same head_email / head_mobile / PAN /
-- AISHE. Same widened predicate as the Data Plane's V17.
CREATE UNIQUE INDEX IF NOT EXISTS idx_cp_inst_apps_head_email_active
    ON institution_applications(head_email)
    WHERE status IN ('approved','pending','rejected');

CREATE UNIQUE INDEX IF NOT EXISTS idx_cp_inst_apps_head_mobile_active
    ON institution_applications(head_mobile)
    WHERE status IN ('approved','pending','rejected');

CREATE UNIQUE INDEX IF NOT EXISTS idx_cp_inst_apps_pan_active
    ON institution_applications(pan)
    WHERE pan IS NOT NULL AND status IN ('approved','pending','rejected');

CREATE UNIQUE INDEX IF NOT EXISTS idx_cp_inst_apps_aishe
    ON institution_applications(aishe_code)
    WHERE aishe_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cp_inst_apps_status
    ON institution_applications(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cp_inst_apps_target_client
    ON institution_applications(target_client_id)
    WHERE target_client_id IS NOT NULL;
