#!/usr/bin/env bash
# wsl-iris-setup.sh — runs INSIDE the WSL Ubuntu distro to provision
# mantra-iris-service. Invoked by install.ps1 via:
#   wsl -d Ubuntu-22.04 --user root -- bash /mnt/c/.../wsl-iris-setup.sh /mnt/c/.../iris-wsl
#
# What this does:
#   1. Enables systemd inside WSL (one-time, requires `wsl --shutdown`).
#   2. Installs JRE 17 + usbip user-tools (for USB passthrough).
#   3. Installs the mantra-iris-service .deb staged on the Windows side.
#   4. Verifies the service starts and reports listening on :8031.
#
# Idempotent — safe to re-run for upgrades or partial recovery.

set -euo pipefail

DEB_DIR="${1:-}"
if [ -z "$DEB_DIR" ] || [ ! -d "$DEB_DIR" ]; then
    echo "✗ usage: wsl-iris-setup.sh <path-to-iris-wsl-dir>" >&2
    echo "  expected to contain mantra-iris-service_*_all.deb" >&2
    exit 1
fi

DEB_FILE=$(ls "$DEB_DIR"/mantra-iris-service_*_all.deb 2>/dev/null | head -n1 || true)
if [ -z "$DEB_FILE" ]; then
    echo "✗ no mantra-iris-service*.deb found in $DEB_DIR" >&2
    echo "  run client-bootstrap/windows/build-bundle.sh on the build host first" >&2
    exit 1
fi

echo "→ provisioning iris service from $(basename "$DEB_FILE")"

# 1. Enable systemd in WSL ---------------------------------------------------
# Without systemd, the .deb's postinst can't `systemctl enable/start` and
# the service won't survive WSL restarts. The `[boot] systemd=true` flag is
# honoured by WSL2 on Win11 + recent Win10 updates.
WSLCONF=/etc/wsl.conf
if ! grep -qE '^systemd=true' "$WSLCONF" 2>/dev/null; then
    echo "→ enabling systemd in /etc/wsl.conf"
    if [ -f "$WSLCONF" ] && grep -qE '^\[boot\]' "$WSLCONF"; then
        sed -i '/^\[boot\]/a systemd=true' "$WSLCONF"
    else
        cat >> "$WSLCONF" <<'EOF'

[boot]
systemd=true
EOF
    fi
    echo "  (systemd will activate after the next 'wsl --shutdown'; we'll trigger this below)"
    NEED_RESTART=1
else
    echo "✓ systemd already enabled in /etc/wsl.conf"
    NEED_RESTART=0
fi

# 2. Install dependencies ----------------------------------------------------
echo "→ apt update + dependency install"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
# default-jre = the iris-service .deb's runtime dependency.
# linux-tools-virtual + hwdata = userspace `usbip` to attach passed-through
# devices (usbipd-win on the Windows side handles the host half).
apt-get install -y --no-install-recommends \
    default-jre-headless \
    linux-tools-virtual \
    hwdata \
    ca-certificates \
    curl

# usbip binary lives under /usr/lib/linux-tools/<version>/usbip on Ubuntu;
# symlink to /usr/local/bin so our scripts find it on $PATH.
USBIP_BIN=$(ls /usr/lib/linux-tools/*/usbip 2>/dev/null | tail -n1 || true)
if [ -n "$USBIP_BIN" ] && [ ! -e /usr/local/bin/usbip ]; then
    ln -sf "$USBIP_BIN" /usr/local/bin/usbip
fi

# 3. Install the iris service .deb ------------------------------------------
# Stop the service first if it's running — `apt-get install --reinstall`
# does this for us in theory, but some old states (failed unit, stale
# pidfile) make the postinst flaky if a process is still bound to :8031.
echo "→ stopping any running mantra-iris-service before (re)install"
systemctl stop mantra-iris-service 2>/dev/null || true

# `--reinstall` forces apt to re-extract the .deb's payload even when
# the version on disk matches. Without this flag, an iteration cycle
# (build new .deb, run install.ps1 again) silently no-ops because apt
# considers the version "already newest" — exactly what bit us when
# fixing the systemd ExecStart classpath issue. `dpkg -i` on the file
# bypasses apt's version compare entirely; we use both for robustness.
echo "→ installing $(basename "$DEB_FILE") (force reinstall)"
dpkg -i "$DEB_FILE" 2>&1 | grep -v "^Reading\|^Building\|^Selecting\|^Preparing\|^Unpacking" || true

# Override the bind address for the WSL2 case. The .deb's systemd unit
# defaults to 127.0.0.1 (correct for native Linux operator laptops where
# we don't want the daemon reachable from the laptop's network), but
# WSL2's NAT-mode localhost-forwarder fails to bridge Windows host
# `localhost:8031` calls to a 127.0.0.1-bound service inside the VM —
# Windows curl returns "Empty reply" / "Connection aborted" (verified
# 2026-05-07 on Windows 10 19045 where mirrored networking isn't
# available). Binding the JVM to 0.0.0.0 inside WSL makes the forwarder
# work, with no real exposure increase: the WSL VM has a private
# Hyper-V vSwitch interface, not a LAN-routed one.
DROPIN_DIR=/etc/systemd/system/mantra-iris-service.service.d
mkdir -p "$DROPIN_DIR"
cat > "$DROPIN_DIR/wsl-bind.conf" <<'EOF'
# Auto-generated by wsl-iris-setup.sh — do not edit by hand.
# Overrides the default 127.0.0.1 bind so WSL2 NAT forwarding from the
# Windows host to localhost:8031 works.
[Service]
Environment=IRIS_BIND=0.0.0.0
EOF
echo "→ wrote WSL bind override at $DROPIN_DIR/wsl-bind.conf"

# Reload systemd so any changes to the unit file (ExecStart, env vars)
# take effect, then bring the service up.
systemctl daemon-reload
systemctl enable mantra-iris-service 2>/dev/null || true
systemctl restart mantra-iris-service 2>/dev/null || true

# 4. Verify --------------------------------------------------------------
# If systemd was JUST enabled, the daemon won't be running yet inside this
# session — needs `wsl --shutdown` from the host. Detect that case and
# advise; otherwise verify systemctl status.
if [ "$NEED_RESTART" -eq 1 ]; then
    echo ""
    echo "⚠ systemd was just enabled; iris service won't start until WSL restarts."
    echo "  install.ps1 will run 'wsl --shutdown' next; the iris service will come up"
    echo "  on first launch of the distro afterwards."
    exit 0
fi

# Give systemd a moment to bring the unit up after install. systemd's
# default Restart=on-failure backoff means a unit that crashes on launch
# can take up to 3-5 seconds (RestartSec * a few attempts) to settle.
sleep 5
if systemctl is-active --quiet mantra-iris-service; then
    echo "✓ mantra-iris-service is running"
    systemctl status mantra-iris-service --no-pager --lines=5 || true
else
    echo ""
    echo "✗ mantra-iris-service did not start. Diagnostics:"
    echo ""
    echo "--- systemctl status ---"
    systemctl status mantra-iris-service --no-pager --lines=10 || true
    echo ""
    echo "--- journalctl (last 40 lines, full message text) ---"
    journalctl -u mantra-iris-service --no-pager --lines=40 -o cat || true
    echo ""
    echo "--- /usr/local/mantra-iris-service/ contents ---"
    ls -la /usr/local/mantra-iris-service/ 2>/dev/null || echo "  (directory missing)"
    echo ""
    echo "--- effective ExecStart (from unit file) ---"
    grep ExecStart /etc/systemd/system/mantra-iris-service.service \
        || grep ExecStart /lib/systemd/system/mantra-iris-service.service \
        || echo "  (unit file not found in expected paths)"
    echo ""
    echo "--- java + classpath sanity ---"
    echo "java: $(which java 2>/dev/null || echo 'NOT ON PATH')"
    java -version 2>&1 | head -3 || true
    echo ""
    echo "Common root causes:"
    echo "  1. Marvis_Auth.jar missing from /usr/local/mantra-iris-service/"
    echo "     (vendor JAR must be staged in iris-service/lib/ before .deb build)"
    echo "  2. systemd ExecStart still using 'java -jar' instead of 'java -cp <jar>:<jar> Main'"
    echo "     (pre-2026-05-06 unit files have this bug — rebuild the .deb)"
    echo "  3. Java not on PATH inside WSL (check 'which java' above)"
    echo "  4. Marvis SDK class names changed — check journalctl for ClassNotFoundException"
    exit 1
fi

# Smoke test the HTTP layer.
if curl -sf -m 3 -X POST http://127.0.0.1:8031/iris/supporteddevicelist >/dev/null; then
    echo "✓ HTTP endpoint responding on :8031"
else
    echo "⚠ HTTP endpoint not yet responding (service may still be starting)"
fi

echo ""
echo "✓ iris provisioning complete."
echo "  Service:   systemctl status mantra-iris-service"
echo "  Logs:      journalctl -u mantra-iris-service -f"
echo "  USB list:  usbip list -p (should show MIS100V2 once usbipd attaches it)"
